let data = [
  {
    id: 1,
    name: "Striped Slim Fit Shirt",
    image: "./images/m1.jpg",
    price: 1000,
    category: "Men",
    size: "XL",
    inStock: true,
  },
  {
    id: 2,
    name: "Full Sleeves Slim Fit Shirt",
    image: "./images/m2.jpg",
    price: 2000,
    category: "Men",
    size: "L",
    inStock: false,
  },
  {
    id: 3,
    name: "Colourblock Crew- Neck T-shirt",
    image: "./images/m3.jpg",
    price: 679,
    category: "Men",
    size: "S",
    inStock: true,
  },
  {
    id: 4,
    name: "Pack of 3 Graphic Print Crew-Neck T-shirts",
    image: "./images/m4.jpg",
    price: 999,
    category: "Men",
    size: "M",
    inStock: true,
  },
  {
    id: 5,
    name: "Straight Track Pants with Insert Pockets",
    image: "./images/m5.jpg",
    price: 599,
    category: "Men",
    size: "XL",
    inStock: false,
  },
  {
    id: 6,
    name: "Printed Saree with Blouse Piece",
    image: "./images/w1.jpg",
    price: 999,
    category: "Women",
    size: "XL",
    inStock: false,
  },
  {
    id: 7,
    name: "Embellished Straight Kurta Set",
    image: "./images/w2.jpg",
    price: 1999,
    category: "Women",
    size: "L",
    inStock: false,
  },
  {
    id: 8,
    name: "Silk Saree with Contrast Border",
    image: "./images/w3.jpg",
    price: 18400,
    category: "Women",
    size: "XXL",
    inStock: true,
  },
  {
    id: 9,
    name: "Floral Print Straight Kurta Set",
    image: "./images/w4.jpg",
    price: 899,
    category: "Women",
    size: "M",
    inStock: true,
  },
  {
    id: 10,
    name: "Indian Anarkali Kurta Set",
    image: "./images/w5.jpg",
    price: 799,
    category: "Women",
    size: "XL",
    inStock: true,
  },
  {
    id: 11,
    name: "Pack of 2 Printed Hooded T-Shirts",
    image: "./images/k1.jpg",
    price: 643,
    category: "Kids",
    size: "L",
    inStock: true,
  },
  {
    id: 12,
    name: "Pack of 3 Printed Round-Neck T-shirts",
    image: "./images/k2.jpg",
    price: 799,
    category: "Kids",
    size: "M",
    inStock: false,
  },
  {
    id: 13,
    name: "Graphic Print Pants with Top",
    image: "./images/k3.jpg",
    price: 299,
    category: "Kids",
    size: "S",
    inStock: true,
  },
  {
    id: 14,
    name: "Indian Print Kurta Pyjama Set",
    image: "./images/k4.jpg",
    price: 899,
    category: "Kids",
    size: "M",
    inStock: true,
  },
  {
    id: 15,
    name: "Floral Print Kurta with Sharara Set",
    image: "./images/k5.jpg",
    price: 399,
    category: "Kids",
    size: "M",
    inStock: true,
  },
];

export default data;
